### ISSUE TITLE
Lecture videos

### ISSUE THREAD

**Issue by tanlaa** [romankuchin/itinfraservices#7]
The lecture videos are a bit of a mess. Timestamps seem a bit random. There is no video of our groups last lecture recording 14.10. Some lectures (including other groups lab5) have no sound whatsoever. As a cherry on the cake - the last video is of an older bearded guy talking to a non-bearded guy about other stuff than IT infra ;)

Would appreciate the recordings for homework reference.

**Comment by hudolejev** [comment]
A bit of mess they are, true.

Not much we can do with video list organization in echo360, this is happening automagically. Will provide direct links to videos though where applicable.
